"""add_timezone_to_datetime_columns

Revision ID: e6241f909849
Revises: a21826898b46
Create Date: 2025-10-17 01:29:45.526647

"""
from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "e6241f909849"
down_revision: Union[str, Sequence[str], None] = "a21826898b46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
