"""add_proposed_check_in_check_out

Revision ID: a21826898b46
Revises: bceaad179931
Create Date: 2025-10-16 23:12:14.793868

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a21826898b46"
down_revision: Union[str, Sequence[str], None] = "bceaad179931"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fichaje", schema=None) as batch_op:
        batch_op.add_column(sa.Column("proposed_check_in", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("proposed_check_out", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fichaje", schema=None) as batch_op:
        batch_op.drop_column("proposed_check_out")
        batch_op.drop_column("proposed_check_in")

    # ### end Alembic commands ###
