"""initial_setup

Revision ID: 2386bdf51fa0
Revises: 
Create Date: 2025-10-14 11:12:40.351486

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '2386bdf51fa0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
