"""add_solicitud_table_and_user_vacation_balance

Revision ID: bceaad179931
Revises: 34c25f9618d2
Create Date: 2025-10-15 19:32:14.457164

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bceaad179931"
down_revision: Union[str, Sequence[str], None] = "34c25f9618d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("solicitud",
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("tipo", sa.Enum("VACATION", "SICK_LEAVE", "PERSONAL", "OTHER", name="solicitudtipo"), nullable=False),
    sa.Column("fecha_inicio", sa.Date(), nullable=False),
    sa.Column("fecha_fin", sa.Date(), nullable=False),
    sa.Column("dias_solicitados", sa.Integer(), nullable=False),
    sa.Column("motivo", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column("status", sa.Enum("PENDING", "APPROVED", "REJECTED", "CANCELLED", name="solicitudstatus"), nullable=False),
    sa.Column("reviewed_by", sa.Integer(), nullable=True),
    sa.Column("reviewed_at", sa.DateTime(), nullable=True),
    sa.Column("comentarios_revision", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(["reviewed_by"], ["user.id"], ),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    with op.batch_alter_table("solicitud", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_solicitud_fecha_fin"), ["fecha_fin"], unique=False)
        batch_op.create_index(batch_op.f("ix_solicitud_fecha_inicio"), ["fecha_inicio"], unique=False)
        batch_op.create_index(batch_op.f("ix_solicitud_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_solicitud_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_solicitud_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("dias_vacaciones_anuales", sa.Integer(), nullable=False, server_default="22"))
        batch_op.add_column(sa.Column("dias_vacaciones_disponibles", sa.Float(), nullable=False, server_default="22.0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("dias_vacaciones_disponibles")
        batch_op.drop_column("dias_vacaciones_anuales")

    with op.batch_alter_table("solicitud", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_solicitud_user_id"))
        batch_op.drop_index(batch_op.f("ix_solicitud_status"))
        batch_op.drop_index(batch_op.f("ix_solicitud_id"))
        batch_op.drop_index(batch_op.f("ix_solicitud_fecha_inicio"))
        batch_op.drop_index(batch_op.f("ix_solicitud_fecha_fin"))

    op.drop_table("solicitud")
    # ### end Alembic commands ###
