"""change_default_days

Revision ID: bca0d8d9e5b8
Revises: bceaad179931
Create Date: 2025-10-16 14:30:09.519250

"""
from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "bca0d8d9e5b8"
down_revision: Union[str, Sequence[str], None] = "bceaad179931"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
